
-- CREATE TABLE TO STORE DATA

CREATE TABLE credit_card_prediction
(ID int not null,
LIMIT_BAL int null,
SEX int null,
EDUCATION int null,
MARRIAGE int null,
AGE int null,
PAYMENT_SEPTEMBER_2005 int null,
PAYMENT_AUGUST_2005 int null,
PAYMENT_JUL_2005 int null,
PAYMENT_JUN_2005 int null,
PAYMENT_MAY_2005 int null,
PAYMENT_APRIL_2005 int null,
AMOUNT_OF_BILL_SEPTEMBER_2005 int null,
AMOUNT_OF_BILL_AUGUST_2005 int null,
AMOUNT_OF_BILL_JUL_2005 int null,
AMOUNT_OF_BILL_JUN_2005 int null,
AMOUNT_OF_BILL_MAY_2005 int null,
AMOUNT_OF_BILL_APRIL_2005  int null,
AMOUNT_PREVIOUS_PAY_SEPTEMBER_2005 int null,
AMOUNT_PREVIOUS_PAY_AUGUST_2005 int null,
AMOUNT_PREVIOUS_PAY_JUL_2005 int null,
AMOUNT_PREVIOUS_PAY_JUN_2005 int null,
AMOUNT_PREVIOUS_PAY_MAY_2005 int null,
AMOUNT_PREVIOUS_PAY_APRIL_2005  int null,
DEFAULT_PAYMENT_NEXT_MONTH int null);